/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h" //系统的用<>  自己的用""
/* Header for class com_shixin_jni_JniTest */

#ifndef _Included_com_shixin_jni_JniTest
#define _Included_com_shixin_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shixin_jni_JniTest
 * Method:    getStringFromc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shixin_jni_JniTest_getStringFromc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
