/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_dongnaoedu_jni_JniTest */

#ifndef _Included_com_dongnaoedu_jni_JniTest
#define _Included_com_dongnaoedu_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dongnaoedu_jni_JniTest
 * Method:    getStringFromC
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_dongnaoedu_jni_JniTest_getStringFromC
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_dongnaoedu_jni_JniTest_getString2FromC
(JNIEnv *, jobject, jint);

JNIEXPORT jstring JNICALL Java_com_dongnaoedu_jni_JniTest_accessField
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_dongnaoedu_jni_JniTest_accessStaticField
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_dongnaoedu_jni_JniTest_accessMethod
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_dongnaoedu_jni_JniTest_accessStaticMethod
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
